### ISSUE TITLE
Error on executing demo.py

### ISSUE THREAD

**Issue by abhattachar5** [lsimmons2/bmi-project#3]
Getting the below error when executing the code:

(base) C:\Users\Administrator\Desktop\Project\bmi-project-master>python demo.py
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from model import get_model
  File "C:\Users\Administrator\Desktop\Project\bmi-project-master\model.py", line 31
    print 'Loaded weights from age classifier'
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Loaded weights from age classifier')?

**Comment by QuietWoods** [comment]
Are you using python3, if it is, change to python3 print format.Like this:
python2 version: print "...."
python3 version: print("....")
